name: .NET CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        include:
          - project: Boid.SourceGenerator.Testing

    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '7.0'

      - name: Pack .NET projects
        env:
          project: ${{ matrix.project }}
        run: |
          read -ra options <<< "--configuration Release -p:PublishTrimmed=false -p:SourceRevisionId=$(git rev-parse --short HEAD)"
          dotnet pack "src/$project" "${options[@]}" -o "build/$project"

      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.project }}
          path: build/${{ matrix.project }}

  tests:
    strategy:
      matrix:
        include:
          - project: Boid.SourceGenerator.Testing

    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '7.0'

      - name: Run tests
        env:
          project: ${{ matrix.project }}
        run: dotnet test "src/$project"